export const FETCH_PROVERBS = 'FETCH_PROVERBS'
export const FETCH_EACH_PROVERB = 'FETCH_EACH_PROVERB'
export const ACTIVE_PROVERB = 'ACTIVE_PROVERB'
export const CREATE_PROVERB = 'CREATE_PROVERB'
export const DELETE_PROVERB = 'DELETE_PROVERB'
export const EDIT_PROVERB = 'EDIT_PROVERB'
export const PUBLISH_PROVERB = 'PUBLISH_PROVERB'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'

export const EDIT_TRANSLATION = 'EDIT_TRANSLATION'
export const DELETE_TRANSLATION = 'DELETE_TRANSLATION'
export const EDIT_INTERPRETATION = 'EDIT_INTERPRETATION'
export const DELETE_INTERPRETATION = 'DELETE_INTERPRETATION'

// Translation
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION'
export const CREATE_TRANSLATION = 'CREATE_TRANSLATION'

// interpretation
export const UPDATE_INTERPRETATION = 'UPATE_INTERPRETATION'
export const CREATE_INTERPRETATION = 'CREATE_INTERPPRETATION'

// Alert Constant
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'